#
#
#
version: '3.8'

services:
  hello_world:
    build:
      context: hello_world
      dockerfile: Dockerfile
    image: phaustin/hello_world:aug20
    labels:
      - "traefik.enable=false"
    container_name: hello_world
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy_aug07
    working_dir: /home/jovyan/dashdir
    command: gunicorn --workers=5 --threads=1 -b 0.0.0.0:8050 app:server
    #command: python app.py


services:
  hydro:
    build:
      context: hydro
      dockerfile: Dockerfile
    image: phaustin/hydro:aug20
    labels:
      - "traefik.enable=false"
    container_name: hydro
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy_aug07
    working_dir: /home/jovyan/dashdir
    command: gunicorn --workers=5 --threads=1 -b 0.0.0.0:8050 app:server
    #command: python app.py



networks:
    proxy_aug07:
      external: true
