name: notebook
channels:
  - eoas_ubc
  - conda-forge
dependencies:
  - python>3.9.0
  - pip>21.0
  - numpy
  - scipy
  - pre-commit
  - cmocean
  - intake
  - git
  - gcsfs
  - setuptools-scm
  - pooch
  - gunicorn
  - flask
  - cartopy
  - mamba
  - intake-esm
  - dash
  - matplotlib
  - jupytext
  - conda-lock
# conda-lock -f environment.yml -p linux-64
